### ISSUE TITLE
cssom parser failing when using @esbuild-kit/cjs-loader

### ISSUE THREAD

**Issue by steabert** [esbuild-kit/cjs-loader#19]
I've ran into a problem using `tsx` and managed to isolate the problem as an issue with `@esbuild-kit/cjs-loader` and `cssom`. When using the loader, the cssom parser fails, but not when using e.g. `esbuild-register` or no loader. I've reproduced the problem and included the necessary files in this issue. However, I'm not knowledgeable enough to know where to look next, so it would be great if I can get some help.

**Comment by steabert** [comment]
[test.zip](https://github.com/esbuild-kit/cjs-loader/files/9387057/test.zip)

**Comment by privatenumber** [comment]
Thanks for the report and reproduction. (Next time, I recommend uploading a repository instead of a zip file.)

I released a fix in https://github.com/esbuild-kit/core-utils/pull/26, you can run `npm update` or re-install tsx to get it.
