### ISSUE TITLE
When debug in vscode using cjs-loader, step into js source code under node_modules cannot show original source

### ISSUE THREAD

**Issue by oliverzy** [esbuild-kit/cjs-loader#31]
![image](https://user-images.githubusercontent.com/1321817/216760756-88b94afc-27b9-4210-992d-e83c449b98c3.png)

The original source is the following:

![image](https://user-images.githubusercontent.com/1321817/216760803-22cd3211-a5d6-47be-a6b6-a1ba0c5993f7.png)

**Comment by privatenumber** [comment]
Maybe this will help:
https://github.com/esbuild-kit/tsx/discussions/61

There's no reproduction so I'm going to close this.
