### ISSUE TITLE
Add support for self-referencing

### ISSUE THREAD

**Issue by RebeccaStevens** [esbuild-kit/cjs-loader#33]
I'm not sure exactly what's happening but [package self-referencing](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name) doesn't seem to work on windows, but it does on ubuntu and macos.

[ubuntu passing test](https://github.com/webpro/knip/actions/runs/4433539584/jobs/7778676820)
[windows failing test](https://github.com/webpro/knip/actions/runs/4433539584/jobs/7778677006)

**Comment by RebeccaStevens** [comment]
This might actually be an issue in node itself.

**Comment by webpro** [comment]
My bad, when using `createRequire`, the argument should be wrapped in `pathToFileURL`. Not doing this leads to issues only in Windows.
