### ISSUE TITLE
Bump get-tsconfig version 

### ISSUE THREAD

**Issue by npdev453** [esbuild-kit/cjs-loader#35]
### Problem

Same problem as here:
https://github.com/privatenumber/get-tsconfig/issues/44#issuecomment-1484315150

### Expected behavior

Tsconfigs with multiple export will not crash with 
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array

### Package manager

pnpm

### Operating system

Linux

**Comment by privatenumber** [comment]
You can just update the get-tsconfig dependency in your project:
https://github.com/esbuild-kit/tsx#theres-an-outdated-dependency-in-tsxcan-you-update
